apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana 
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest # official Grafana docker image
        ports:
        - containerPort: 3000 
        env: # environment variables to pass into container on boot
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin" # username is admin
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring
spec:
  type: NodePort 
  selector:
    app: grafana #
  ports:
  - port: 3000 # internal service port
    targetPort: 3000 # container port
    nodePort: 30300 # map port 30300 on EC2 public IP straight to port 3000 inside container