resource "aws_route53_zone" "main" {
  name = "omaralqinneh.me"
  
  tags = {
    Description = "Managed by Terraform for Cloud Resume Challenge"
  }
}

# Output NS for name cheap DNS
output "name_servers" {
  description = "The new Name Servers generated by AWS"
  value       = aws_route53_zone.main.name_servers
}